---
- name: Install Java
  package:
    name: "{{ java_package }}"
    state: present

- name: Install other dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ dependencies }}"

- name: Install epel in ec2
  shell: "amazon-linux-extras install epel -y"

- name: Add repo
  yum_repository:
    name: jenkins
    description: Jenkins YUM repo
    baseurl: "{{ jenkins.baseurl }}"
    gpgcheck: yes

- name: Add daemonize repo
  yum_repository:
   name: daemonize
   description: Daemonize repo
   baseurl: "{{ daemonize_baseurl }}"
   gpgcheck: no
   enabled: yes

- name: Add jenkins gpg key
  rpm_key:
    key: "{{ jenkins.key }}"
    state: present
 
- name: Install Jenkins
  package:
    name: jenkins
    state: present

- name: Check jenkins directory
  stat:
    path: /tmp/jenkins.tar.gz
  register: jenkins_tar

- name: Copy jenkins directory
  copy:
    src: files/jenkins.tar.gz
    dest: /tmp/
  when: jenkins_tar.stat.exists == False

- name: Unarchive jenkins directory into /var/lib/jenkins
  unarchive:
    src: /tmp/jenkins.tar.gz
    dest: /var/lib/
    remote_src: yes

- name: Give jenkins permission
  file:
    path: /var/lib/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
